import type { Metadata } from "next";
import { cookies } from 'next/headers'

import { Header, Providers, Betslip } from '@/components';

import '@rainbow-me/rainbowkit/styles.css'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies()

  const initialChainId = cookieStore.get('appChainId')?.value

  return (
    <html lang="en">
      <body>
        <Providers initialChainId={initialChainId}>
          <div className="md:max-w-[1040px] mx-auto">
            <Header />
            <main>
              {children}
              <Betslip />
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
